config/routes.rb
Harvest::Application.routes.draw do

  match '/employee/:id', to: 'welcome#employee', via: [:get, :post], as: :employee
  root 'welcome#index'

end

app/models/concerns/harvest_base.rb
class HarvestBase

  def client
    @harvest ||= Harvest.client( subdomain: Harvest::Application::CONFIG['harvest']['subdomain'],  username: Harvest::Application::CONFIG['harvest']['login_email'],  password: Harvest::Application::CONFIG['harvest']['password'])
  end
end

app/models/concerns/user_entries.rb
class UserEntries < HarvestBase

  def initialize(user_id, date = Date.today)
    @user_id = user_id
    @day = date
  end

  def start_date
    @day.beginning_of_week
  end

  def end_date
    @day.end_of_week
  end

  def entries
    @entries ||= get_entries
  end

  def user
    @user ||= client.users.find(@user_id)
  end

  def hours
    @hours ||= entries.map{ |entry| entry[:times].map{ |t| t.hours } }.flatten.sum
  end

  private

    # def  get_hours
    #   get_hours = 0.00

    # entries.each do |entry|
    #   entry.times.each do |t|
    #     @hours += t.hours
    #   end
    # end

    # @hours

    # end
    def get_entries

      entries = []
      date = start_date.dup

      while date <= end_date
        entries << { :date => date, :times => client.time.all(date, user.id) }
        date += 1.day
      end

      entries

    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/person.rb
class Person

  attr_accessor :times
  attr_accessor :info

  def initialize(options = {})
    @info = options[:info] || []
    @times = options[:times] || []
  end

  def id
    @info.id
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :set_defaults

  def index
    @users = Harvest::Application::CONFIG['user_emails'].to_s.gsub(' ', '').split(',').inject({}) { |h, elem| h[elem] = nil; h}

    if @users.empty?
      @harvest.users.all.each do |user|
        @users[u.email] = Person.new(info: user, times: @harvest.time.all(@day, user.id))
      end
    else
      all_harvest_users = @harvest.users.all

      @users.each do |k,v|
        all_harvest_users.select{|user| user.email == k }.each do |user|
          @users[k] = Person.new(info: user, times: @harvest.time.all(@day, user.id))
        end
      end
    end
  end

  def employee
    @entries = UserEntries.new(params[:id], @day)
  end

  private

    def set_defaults
      @day = Chronic.parse(params[:date]) || previous_day
      @harvest = Harvest.client( subdomain: Harvest::Application::CONFIG['harvest']['subdomain'],  username: Harvest::Application::CONFIG['harvest']['login_email'],  password: Harvest::Application::CONFIG['harvest']['password'])
    end

    def previous_day
      d = 1.day.ago
      # 0..6, Sun..Sat
      while d.wday < 1 || d.wday > 5
        d = d - 1.day
      end
      d
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_url(email)
    gravatar_id = Digest::MD5::hexdigest(email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Harvest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="wrapper">
    <%= yield %>
  </div>

  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.5.18/webfont.js"></script>
  <script>
    WebFont.load({
      google: {
        families: ['Roboto:400,700']
      }
    });
  </script>
</body>
</html>

app/views/welcome/employee.html.haml
.right
  %form
    = text_field_tag 'date', @day.strftime("%m/%d/%Y"), class: 'datepicker'
    = submit_tag "GO"
%h1
  = link_to 'Harvest', root_path

  = link_to '&#9664;'.html_safe, employee_path(date: @entries.start_date.advance(weeks: -1).strftime("%m/%d/%Y")), class: 'advance-arrow'
  \: Weekly Report
  = link_to '&#9658;'.html_safe, employee_path(date: @entries.start_date.advance(weeks: 1).strftime("%m/%d/%Y")), class: 'advance-arrow'


%hr


  .right{:style => "margin-top: 4px"}

  %p.right
    %strong Total:
    = link_to number_with_precision(@entries.hours, precision: 2), "https://tgfi.harvestapp.com/time/week/#{@entries.start_date.year}/#{@entries.start_date.month.to_s.rjust(2, '0')}/#{@entries.start_date.day.to_s.rjust(2, '0')}/#{@entries.user.id}", :target => "_blank"

  %h1
    = image_tag gravatar_url(@entries.user.email), :size => "30x30"
    #{@entries.user.first_name} #{@entries.user.last_name}


  - @entries.entries.each do |entry|

    %h2 #{entry[:date].strftime("%A, %B %d")}
    %ul
      - entry[:times].each do |t|
        %li
          .right= number_with_precision(t.hours, precision: 2)
          %h4
            = t.project
            .company (#{t.client})

          %p #{t.task} - #{t.notes}
    %p.right
      %strong Total:
      = number_with_precision(entry[:times].map{ |t| t.hours }.flatten.sum, precision: 2)
    %br{ :clear => 'all' }
    %hr


  %p= @entries.user.type



  :javascript
    $(function() {
        $( ".datepicker" ).datepicker();
      });

app/views/welcome/index.html.haml
.right
  %form
    = text_field_tag 'date', @day.strftime("%m/%d/%Y"), class: 'datepicker'
    = submit_tag "GO"
%h1
  = link_to '&#9664;'.html_safe, root_path(date: 1.business_days.before(@day).strftime("%m/%d/%Y")), class: 'advance-arrow'
  Harvest: #{@day.strftime("%A, %B %d")}
  = link_to '&#9658;'.html_safe, root_path(date: 1.business_days.after(@day).strftime("%m/%d/%Y")), class: 'advance-arrow'
%hr

- @users.each do |email,user|
  - total = 0.00
  .right{:style => "margin-top: 4px"}= link_to 'edit', "https://tgfi.harvestapp.com/time/day/#{@day.year}/#{@day.month.to_s.rjust(2, '0')}/#{@day.day.to_s.rjust(2, '0')}/#{user.info.id}", :target => "_blank"
  %h1
    = image_tag gravatar_url(email), :size => "30x30"
    = link_to "#{user.info.first_name} #{user.info.last_name}", "/employee/#{user.info.id}"

  %p= user.info.type
  %ul
    - user.times.each do |t|
      %li
        .right= number_with_precision(t.hours, precision: 2)
        %h4
          = t.project
          .company (#{t.client})

        %p #{t.task} - #{t.notes}
        - total += t.hours

  %p.right
    %strong Total:
    = number_with_precision(total, precision: 2)
  %br{ :clear => 'all' }
  %hr

  :javascript
    $(function() {
        $( ".datepicker" ).datepicker();
      });
      </script>